site_name: Curso Django Completo
nav:
  - Inicio: index.md
  - Django:
      - Modelos: django/modelos.md
  - Paquetes:
      - Extensiones Esenciales: paquetes/extensiones.md
  - Primeros Pasos:
      - Configuraci贸n Inicial: primeros-pasos/configuracion-inicial.md
      - Usuarios, Autenticaci贸n y Perfiles: primeros-pasos/usuarios-autenticacion-perfiles.md
  - Produccion:
      - Configuraci贸n para Producci贸n: produccion/preparar-produccion.md